version: 2.1

executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: daewok/lisp-devel

commands:
  persist-workspace:
    steps:
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - ./*
  attach-workspace:
    steps:
      - attach_workspace:
          at: ~/workspace

jobs:
  setup:
    executor:
      name: default
    steps:
      - checkout

workflows:
  version: 2
  build:
    jobs:
      - setup
